# Generated by Django 4.0.4 on 2022-05-31 22:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lobi',
            name='ime',
            field=models.CharField(default='lobi_default', max_length=30),
        ),
        migrations.AlterField(
            model_name='lobi',
            name='idkor2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_idkor2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='partija',
            name='first_turn',
            field=models.IntegerField(default=1),
        ),
    ]
