# Generated by Django 4.0.4 on 2022-05-18 01:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_korisnik_korisnickoime'),
    ]

    operations = [
        migrations.CreateModel(
            name='Igra',
            fields=[
                ('idigra', models.AutoField(db_column='idIgra', primary_key=True, serialize=False)),
                ('tipigre', models.CharField(choices=[('trening', 'Trening'), ('duel', 'Duel')], max_length=45)),
                ('ishod', models.IntegerField(choices=[(-1, 'Igrac 1 pobeda'), (0, 'Nereseno'), (1, 'Igrac 2 pobeda')], default=0)),
            ],
            options={
                'db_table': 'Igra',
            },
        ),
        migrations.CreateModel(
            name='Rec',
            fields=[
                ('idrec', models.AutoField(db_column='idRec', primary_key=True, serialize=False)),
                ('rec', models.CharField(max_length=45, unique=True)),
                ('tezina', models.IntegerField(choices=[(0, 'Laka rec'), (1, 'Srednja rec'), (2, 'Teska rec')])),
            ],
        ),
        migrations.CreateModel(
            name='Lobi',
            fields=[
                ('idigra', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts.igra')),
                ('tip', models.CharField(choices=[('osnovni', 'Osnovni korisnik'), ('vip', 'VIP korisnik')], default='osnovni', max_length=30)),
                ('status', models.CharField(choices=[('otvoren', 'Otvoren lobi'), ('u toku', 'Igra u toku')], default='otvoren', max_length=30)),
                ('idkor1', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_idkor1', to=settings.AUTH_USER_MODEL)),
                ('idkor2', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_idkor2', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'lobi',
            },
        ),
        migrations.CreateModel(
            name='Trening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idigra', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.igra')),
                ('idkor', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('idrec', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.rec')),
            ],
            options={
                'db_table': 'Trening',
            },
        ),
        migrations.CreateModel(
            name='Potez',
            fields=[
                ('idpotez', models.AutoField(db_column='idPotez', primary_key=True, serialize=False)),
                ('ishod', models.BooleanField()),
                ('idigra', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.igra')),
                ('idkor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_idkor+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Partija',
            fields=[
                ('idigra', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts.igra')),
                ('brojzivota1', models.IntegerField()),
                ('brojzivota2', models.IntegerField()),
                ('idkor1', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='idkor1', to=settings.AUTH_USER_MODEL)),
                ('idkor2', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='idkor2', to=settings.AUTH_USER_MODEL)),
                ('idlobi', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.lobi')),
                ('idrec1', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='idrec1', to='accounts.rec')),
                ('idrec2', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='idrec2', to='accounts.rec')),
            ],
            options={
                'db_table': 'Partija',
            },
        ),
    ]
