# Generated by Django 4.0.4 on 2022-05-31 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_lobi_ime_alter_lobi_idkor2_alter_partija_first_turn'),
    ]

    operations = [
        migrations.AddField(
            model_name='lobi',
            name='tezina',
            field=models.IntegerField(choices=[(0, 'Laka rec'), (1, 'Srednja rec'), (2, 'Teska rec')], null=True),
        ),
    ]
