# Generated by Django 4.0.4 on 2022-06-02 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_lobi_tezina'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partija',
            name='first_turn',
            field=models.IntegerField(default=0),
        ),
    ]
