# Generated by Django 4.0.4 on 2022-05-18 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_igra_rec_lobi_trening_potez_partija'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='potez',
            table='potez',
        ),
        migrations.AlterModelTable(
            name='rec',
            table='rec',
        ),
    ]
