# Generated by Django 4.0.4 on 2022-05-18 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_potez_table_alter_rec_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rec',
            name='tezina',
            field=models.IntegerField(choices=[(0, 'Laka rec'), (1, 'Srednja rec'), (2, 'Teska rec')], null=True),
        ),
    ]
