# Generated by Django 4.0.4 on 2022-05-19 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_rec_tezina'),
    ]

    operations = [
        migrations.AlterField(
            model_name='igra',
            name='ishod',
            field=models.IntegerField(choices=[(-2, 'U toku'), (-1, 'Igrac 1 pobeda'), (0, 'Nereseno'), (1, 'Igrac 2 pobeda')], default=-2),
        ),
    ]
