# Generated by Django 4.0.4 on 2022-05-19 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_igra_ishod'),
    ]

    operations = [
        migrations.AddField(
            model_name='potez',
            name='idrec',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_idrec+', to='accounts.rec'),
        ),
    ]
