# Generated by Django 4.0.4 on 2022-05-19 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_potez_idrec'),
    ]

    operations = [
        migrations.AddField(
            model_name='potez',
            name='slovo',
            field=models.CharField(default='#', max_length=1),
        ),
    ]
