# Generated by Django 4.0.4 on 2022-06-01 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_partija_idkor2_alter_partija_idrec2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partija',
            name='brojzivota1',
            field=models.IntegerField(default=6),
        ),
        migrations.AlterField(
            model_name='partija',
            name='brojzivota2',
            field=models.IntegerField(default=6),
        ),
    ]
