# Generated by Django 4.0.4 on 2022-06-01 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_partija_brojzivota1_alter_partija_brojzivota2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partija',
            name='idlobi',
        ),
        migrations.AddField(
            model_name='lobi',
            name='idpartija',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='idlobi', to='accounts.partija'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='partija',
            name='first_turn',
            field=models.IntegerField(default=1),
        ),
    ]
