-- MySQL Script generated by MySQL Workbench
-- Wed 20 Apr 2022 18:11:31 CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema CikPogodi
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema CikPogodi
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `CikPogodi` ;
USE `CikPogodi` ;

-- -----------------------------------------------------
-- Table `CikPogodi`.`Korisnik`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CikPogodi`.`Korisnik` (
  `idKor` INT NOT NULL AUTO_INCREMENT,
  `korisnickoIme` VARCHAR(45) NOT NULL,
  `lozinka` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `tipKorisnika` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idKor`),
  UNIQUE INDEX `idKor_UNIQUE` (`idKor` ASC) VISIBLE,
  UNIQUE INDEX `KorisnickoIme_UNIQUE` (`korisnickoIme` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CikPogodi`.`Igrac`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CikPogodi`.`Igrac` (
  `idKor` INT NOT NULL AUTO_INCREMENT,
  `brojPartija` INT NOT NULL DEFAULT 0,
  `brojPobeda` INT NOT NULL DEFAULT 0,
  `blokiran` TINYINT NOT NULL,
  PRIMARY KEY (`idKor`),
  CONSTRAINT `idKor`
    FOREIGN KEY (`idKor`)
    REFERENCES `CikPogodi`.`Korisnik` (`idKor`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CikPogodi`.`Administrator`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CikPogodi`.`Administrator` (
  `idKor` INT NOT NULL AUTO_INCREMENT,
  `Ime` VARCHAR(45) NOT NULL,
  `Prezime` VARCHAR(45) NOT NULL,
  UNIQUE INDEX `idKor_UNIQUE` (`idKor` ASC) VISIBLE,
  PRIMARY KEY (`idKor`),
  CONSTRAINT `idKor`
    FOREIGN KEY (`idKor`)
    REFERENCES `CikPogodi`.`Korisnik` (`idKor`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CikPogodi`.`Rec`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CikPogodi`.`Rec` (
  `idRec` INT NOT NULL AUTO_INCREMENT,
  `rec` VARCHAR(45) NOT NULL,
  `tezina` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idRec`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CikPogodi`.`Lobi`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CikPogodi`.`Lobi` (
  `idLobi` INT NOT NULL AUTO_INCREMENT,
  `tip` VARCHAR(45) NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  `idKor1` INT NOT NULL,
  `idKor2` INT NOT NULL,
  PRIMARY KEY (`idLobi`),
  INDEX `idKor1_idx` (`idKor1` ASC) VISIBLE,
  INDEX `idKor2_idx` (`idKor2` ASC) VISIBLE,
  CONSTRAINT `idKor1`
    FOREIGN KEY (`idKor1`)
    REFERENCES `CikPogodi`.`Igrac` (`idKor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idKor2`
    FOREIGN KEY (`idKor2`)
    REFERENCES `CikPogodi`.`Igrac` (`idKor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CikPogodi`.`Igra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CikPogodi`.`Igra` (
  `idIgra` INT NOT NULL AUTO_INCREMENT,
  `tipIgre` VARCHAR(45) NOT NULL,
  `ishod` INT NOT NULL,
  PRIMARY KEY (`idIgra`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CikPogodi`.`Partija`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CikPogodi`.`Partija` (
  `idIgra` INT NOT NULL AUTO_INCREMENT,
  `idRec1` INT NOT NULL,
  `idRec2` INT NOT NULL,
  `brojZivota1` INT NOT NULL DEFAULT 10,
  `brojZivota2` INT NOT NULL DEFAULT 10,
  `idLobi` INT NOT NULL,
  PRIMARY KEY (`idIgra`),
  INDEX `idRec1_idx` (`idRec1` ASC) VISIBLE,
  INDEX `idRec2_idx` (`idRec2` ASC) VISIBLE,
  INDEX `idLobi_idx` (`idLobi` ASC) VISIBLE,
  CONSTRAINT `idRec1`
    FOREIGN KEY (`idRec1`)
    REFERENCES `CikPogodi`.`Rec` (`idRec`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idRec2`
    FOREIGN KEY (`idRec2`)
    REFERENCES `CikPogodi`.`Rec` (`idRec`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idLobi`
    FOREIGN KEY (`idLobi`)
    REFERENCES `CikPogodi`.`Lobi` (`idLobi`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idIgra`
    FOREIGN KEY (`idIgra`)
    REFERENCES `CikPogodi`.`Igra` (`idIgra`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CikPogodi`.`Potez`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CikPogodi`.`Potez` (
  `idPotez` INT NOT NULL AUTO_INCREMENT,
  `idIgra` INT NOT NULL,
  `idKor` INT NOT NULL,
  `ishod` TINYINT NOT NULL,
  PRIMARY KEY (`idPotez`),
  INDEX `idKor_idx` (`idKor` ASC) VISIBLE,
  INDEX `idIgra_idx` (`idIgra` ASC) VISIBLE,
  CONSTRAINT `idIgra`
    FOREIGN KEY (`idIgra`)
    REFERENCES `CikPogodi`.`Igra` (`idIgra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idKor`
    FOREIGN KEY (`idKor`)
    REFERENCES `CikPogodi`.`Igrac` (`idKor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CikPogodi`.`Trening`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CikPogodi`.`Trening` (
  `idIgra` INT NOT NULL AUTO_INCREMENT,
  `idRec` INT NOT NULL,
  `idKor` INT NOT NULL,
  PRIMARY KEY (`idIgra`),
  INDEX `idRec_idx` (`idRec` ASC) VISIBLE,
  INDEX `idKor_idx` (`idKor` ASC) VISIBLE,
  CONSTRAINT `idIgra`
    FOREIGN KEY (`idIgra`)
    REFERENCES `CikPogodi`.`Igra` (`idIgra`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `idRec`
    FOREIGN KEY (`idRec`)
    REFERENCES `CikPogodi`.`Rec` (`idRec`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idKor`
    FOREIGN KEY (`idKor`)
    REFERENCES `CikPogodi`.`Igrac` (`idKor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
